version: "3.8"  # It's good to include a version for clarity

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

    working_dir: /var/www/html
    command: bash -c "docker-php-ext-install pdo pdo_pgsql && apache2-foreground"

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: ["composer"]

  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mvc_project
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
